development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: client-1-dev
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: client-1-test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: client-1-prod
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock